name: Git

on: pull_request

jobs:
  block-fixup:
    runs-on: ubuntu-latest

    steps:
      - name: Block Autosquash Commits
        uses: xt0rted/block-autosquash-commits-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
