# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:  
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Commit message validator
      id: commit-message-validator
      uses: jsedlace/commit-message-validator@master
      env: # Or as an environment variable
        JIRA_TOKEN: ${{ secrets.jira_token }}
        GH_TOKEN: ${{ secrets.github_token }}
        JIRA_USER: jiri.sedlacek@wandera.com
        JIRA_HOST: snappli.atlassian.net

  block-fixup:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.0.0
    - name: Block Fixup Commit Merge
      uses: 13rac1/block-fixup-merge-action@v1.1.1
